.github/workflows/commitlint.yml
README.md
RELEASE.md
imx-core-sdk-kotlin-jvm/generated/src/main/kotlin/com/immutable/sdk/BuildConfig.java
version.yml

Update guide to show how to import from the GitHub package
Using a GitHub package via maven requires extra set up steps and needs to be outlined explicitly.
Also bumped the version.

docs: update installation guide

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableXSdk.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/Crypto.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/BuyWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/CancelWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/SellWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/TransferWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/Workflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/BuyWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/CancelWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/SellWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/TransferWorkflowTest.kt

Update all workflows to add the ethSignature and ethAddress headers to the transaction requests.
Currently the ethSignature and ethAddress headers are optional but will be required in the future, this is in preparation for  that change.
Also changed the workflows to return the full response and not just the id.

feat: add ethSignature to workflows requests

---

.openapi-generator/templates/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
README.md
imx-core-sdk-kotlin-jvm/generated/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt
imx-core-sdk-kotlin-jvm/packages.md
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableXCore.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/BuyCryptoWorkflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/ImmutableXCoreTest.kt

Renamed `ImmutableXSdk` to `ImmutableXCore`.
This change is to keep consistent with naming on other platforms. It's also unusual for a class to include Sdk in the name.

refactor: rename ImmutableXSdk to ImmutableXCore

---

imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/crypto/StarkKeyTest.kt

This test has a signature that requires extra grinding to generate the keys, which is an important area to be covered.

chore: add test for extra grinding

---

CHANGELOG.md
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableXCore.kt

Renamed `cancel` to `cancelOrder` as it was unclear by name what it was cancelling.
Also fixed the return docs on `cancelOrder` and `sell`

refactor: rename cancel to cancelOrder

---

README.md
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableXCore.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/BuyCryptoWorkflow.kt

Update buyCrypto docs to better describe what it does.
Before converting this library to be platform agnostic `buyCrypto` launched a Chrome Custom Tab for Android.
Also added language tags to some README snippets.

docs: fix buyCrypto comments

---

CHANGELOG.md
README.md
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableXCore.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/Signer.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/StandardStarkSigner.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/StarkKey.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/CancelWorkflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/ImmutableXCoreTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/StandardStarkSignerTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/CancelWorkflowTest.kt
sample/src/main/java/com/immutable/sdkdemo/SdkDemo.kt

Added `StandardStarkSigner` as the default implementation to use for `StarkSigner`.
- Changed `StarkKey.sign` to be private as it should only be used via the StarkSigner implementation
- Added tests to `ImmutableXCore` to make sure parameters are correctly being passed to the workflows which already have tests

feat: add StandardStarkSigner

---

CHANGELOG.md
build.gradle
imx-core-sdk-kotlin-jvm/build.gradle
imx-core-sdk-kotlin-jvm/packages.md
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/Crypto.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/StarkKey.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/extensions/ECKeyPair.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/model/SignableTokenData.kt
sample/build.gradle

Add dokka plugin and update code comments.
- For dokka to work the kotlin plugin needed to be explicitly set as a dependency. 
- Removed public visibility from `Crypto` object and `getStarkPublicKey` extension
- Adding dokka to be auto-generate API reference docs to be added to the Immutable docs for this SDK

docs: add dokka and update comments

---

README.md
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableXCore.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/ImmutableXCoreTest.kt

- Get deposit function
- Refactored `ImmutableXCore` to a class so that we can instantiate the `depositApi` (and any other APIs) only once with the correct environment
`depositsApi.getDeposit(id)` vs `DepositsApi().getDeposit(id)`

feat: get deposit

---

contracts/IERC721.sol
imx-core-sdk-kotlin-jvm/src/main/java/com/immutable/sdk/contracts/IERC721_sol_IERC721.java
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/DepositWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/deposit/DepositErc721Workflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/deposit/DepositEthWorkflow.kt

* Added IERC721 smart contract
* Added auto generated IERC721 wrapper
* Deposit ERC721 workflow
* Refactored `executeDeposit` function
* Separated "register and deposit" and 'deposit' into two functions 
* This is because to "register and deposit" ERC721, **registration** contact is required instead of the **core** contract
* Updated deposit ETH workflow to use `depositEth` contract function instead of `deposit`

feat: deposit ERC721

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/ImxTimestamp.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/ImxTimestampTest.kt

Fix signing an incorrect representation of the timestamp for authorised requests.
The message to be signed needs to be a recent timestamp formatted in seconds.

fix: requests that require a timestamp

---

imx-core-sdk-kotlin-jvm/build.gradle
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/Constants.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/StandardStarkSigner.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/StarkCurve.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/StarkKey.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/extensions/Web3j.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/StandardStarkSignerTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/crypto/StarkKeyTest.kt

- Modify `StandardStarkSigner` to take a private key
- Add `StarkKey.generateStarkPrivateKey`
- Removed all key derivation code 
- Changed `Web3j.getNonce` to internal

feat: add generateStarkPrivateKey method

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/DepositWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/EncodeAsset.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/RegisterWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/TransferWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/WithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/Workflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/withdrawal/CompleteEthWithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/withdrawal/PrepareWithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/DepositWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/TransferWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/WithdrawalWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/withdrawal/PrepareWithdrawalWorkflowTest.kt

* Complete ETH withdrawal workflow
* Moved "encode asset" step from `DepositWorkFlow.kt` to a separate file so it can be reused in complete withdrawal workflows
* Refactored hardcoded "UNREGISTERED_USER" to a constant
* Fixed transfer workflow 'amount' and added tests
* Fixed prepare withdrawal workflow 'amount' and added tests
* When sending a transaction, check for errors (`Workflow.kt`)

Complete ETH withdrawal

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/CancelWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/ImxTimestamp.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/WithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/withdrawal/CompleteEthWithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/ImxTimestampTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/WithdrawalWorkflowTest.kt

* Withdraw ERC20 -  Refactored withdraw ETH workflow so that it can be used for withdrawing ERC20
* Removed unused 'amount' from complete withdrawal workflow functions
* Refactored ImxTimestamp and added another unit test case
* Refactored cancel workflow

feat: withdraw ERC20

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/DepositWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/RegisterWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/WithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/Workflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/deposit/DepositErc20Workflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/deposit/DepositErc721Workflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/deposit/DepositEthWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/withdrawal/CompleteErc721WithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/withdrawal/CompleteFungibleTokenWithdrawalWorkflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/DepositWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/WithdrawalWorkflowTest.kt

- Allow users to set gas for functions that interact with contracts (`deposit`, `withdraw` and `isRegisteredOnChain`) since the gas is automatically set by the SDK (using `DefaultGasProvider` might be too low).
- Refactor deposit workflow so there is no need to create another `CompletableFuture` to wrap the chain of `CompletableFuture`s

feat: allow users to set gas for functions that interact with contracts

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/DepositWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/RegisterWorkflow.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/deposit/DepositErc721Workflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/DepositWorkflowTest.kt

Fixed "Register and Deposit ERC721" workflow.
The proxy registration contract method registerAndDepositNft currently fails ownership check in the ERC-721 transfer method. This workaround performs the register and deposit method calls separately.
- `N/A`

fix: register and deposit ERC721

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/StarkKey.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/crypto/StarkKeyTest.kt

Add method to deterministically generate Stark private key
Adding this method to ensure that existing customers that want to generate their stark key deterministically, there is a way to do that by passing in the previously used seed.
- `N/A`

feat: generate legacy key pair

---

.github/workflows/release.yml
build.gradle

* Enable manual trigger of release action and restrict who can run it.
* Update Kotlin Gradle plugin
- `N/A`

ci: release action

---

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/Constants.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/StarkKey.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/crypto/StarkKeyTest.kt

Update `generateLegacyStarkPrivateKey` function to take in a `signer` instead of a seed and address.
To align with the Swift and TS Core SDK.
- `N/A`

feat: update generateLegacyStarkPrivateKey to take in a signer

---

CHANGELOG.md
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/Signer.kt
imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/Workflow.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/DepositWorkflowTest.kt
imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/WithdrawalWorkflowTest.kt

Change `Signer` `signTransaction` to `sendTransaction`.
When integrating the Core SDK with the Wallet SDK, I found that most wallets don’t allow `eth_signTransaction` to sign raw transactions. This limitation means we cannot implement the `signTransaction` in the Wallet SDK. The fix is to use `eth_sendTransaction` in the WalletSDK instead, and therefore the `Signer` `signTransaction` method needs to change to `sendTransaction`.
- Purposely kept `Workflow` `sendTransaction` to return `EthSendTransaction` (instead of changing it to a string for transaction hash) as it is clearer to understand. 
- Examples and README will be updated in another PR when I prepare for the release.
- `N/A`

refactor: change signer sign transaction method to send transaction

---

README.md

This adds a section to the README referencing where to find example code in this repo
Jira: https://immutable.atlassian.net/browse/DX-1698
To make it easier for developers using this SDK to find examples

[DX-1698] Add section linking to examples in README
