immutable/imx-core-sdk-kotlin-jvm

.github/workflows/changelog.yml
Add the changelog workflow back while we manually perform releases.
=> ci: add changelog workflow

README.md
Two of the most common ways to perform async tasks are RxJava and Coroutines. We should provide guidance on how to use the workflows `CompletableFuture` results with these frameworks.
=> docs: how to wrap completablefuture

CHANGELOG.md, README.md, gradle.properties, imx-core-sdk-kotlin-jvm/build.gradle, imx-core-sdk-kotlin-jvm/generated/src/main/kotlin/com/immutable/sdk/BuildConfig.java, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/Crypto.kt, version.yml
Update version and changelog for 0.6.0 release to Maven Central.
Modified release tasks and repositories so this SDK can be uploaded to Maven Central instead of GitHub packages.
=> build: v0.6.0

README.md, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableConfig.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableXCore.kt
* Added support for Sandbox environment.
* Sandbox Moonpay configuration details are the same as Ropsten for now
=> feat: add Sandbox environment

.openapi-generator/templates/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, imx-core-sdk-kotlin-jvm/generated/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/ImmutableXTest.kt
- Add getUser api.
- Renamed ImmutableXCore to ImmutableX to achieve parity with Typescript SDK
- Make api objects lazy instantiation
=> feat: add getUser api

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/ImxTimestamp.kt, sample/src/main/java/com/immutable/sdkdemo/SdkDemo.kt
- Add Collection APIs to `ImmutableX`
- Create a helper for APIs that require a timestamp to be generated as per https://docs.x.immutable.com/docs/generate-imx-signature/
=> feat: add Collection apis

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt
Added wrapped apis for: assets, balances, metadata, mints, projects, and withdrawals.
=> feat: add 6 more api groups

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/TransferWorkflow.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/ImmutableXTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/TransferWorkflowTest.kt
Refactor `transfer` workflow to take in a list and expose a `batchTransfer` method in `ImmutableX`
=> feat: add batchTransfer workflow

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/DepositWorkflow.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/Workflow.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/DepositWorkflowTest.kt
* Unit tests for deposit workflow (ETH, ERC20, ERC721)
=> test: deposit workflow

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/deposit/DepositErc721Workflow.kt
* Fix up contract address to approve
* `registerAndDepositNft` last parameter should be the token ID not the amount
=> fix: register and deposit ERC721 parameters

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/RegisterWorkflow.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/DepositWorkflowTest.kt
* Update deposit workflow unit tests so that it verifies the parameters too
* Refactored register workflow `isRegisteredOnChain` - convert stark public key string to BigInteger
=> test: verify deposit workflow function call parameters

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/Workflow.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/withdrawal/PrepareWithdrawalWorkflow.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/DepositWorkflowTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/withdrawal/PrepareWithdrawalWorkflowTest.kt
* Prepare withdraw
* Added additional test case to deposit workflow
* Clean up println
=> Prepare withdrawal

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/crypto/StarkKey.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/StandardStarkSignerTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/crypto/StarkKeyTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/extensions/JsonObjectExtensionsTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/extensions/ResponseExtensionsTest.kt
Increase code coverage by adding unit tests for:
* Generating stark private key
* Standard stark signer get address
* Extensions
=> Increase code coverage

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/CreateTradeWorkflow.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/CreateTradeWorkflowTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/RegisterWorkflowTest.kt
Added more unit tests for Create Trade and Register workflows
=> Workflow tests

imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/ImmutableXTest.kt
More unit tests for core SDK public functions
=> test: public functions

imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/ImmutableX.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/api/model/UnsignedMintRequest.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/extensions/LinkedHashMap.kt, imx-core-sdk-kotlin-jvm/src/main/kotlin/com/immutable/sdk/workflows/MintWorkflow.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/ImmutableXTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/extensions/LinkedHashMapExtensionsTest.kt, imx-core-sdk-kotlin-jvm/src/test/kotlin/com/immutable/sdk/workflows/MintWorkflowTest.kt
* Mint workflow
* Unit tests for mint workflow
=> feat: mint workflow

.github/workflows/release.yml
Github Action to release the SDK.
- `N/A`
=> ci: release github action

.github/workflows/release.yml, imx-core-sdk-kotlin-jvm/build.gradle
Use system environments instead of of gradle properties.
- `N/A`
=> ci: use system environments for release

.github/workflows/release.yml, CHANGELOG.md
Add 'Unreleased' section to the chang log.
- `N/A`
=> docs: add unreleased section to changelog

.github/workflows/release.yml, CHANGELOG.md, README.md, imx-core-sdk-kotlin-jvm/generated/src/main/kotlin/com/immutable/sdk/BuildConfig.java, version.yml
Documentation updates for v1.0.0-beta.2.
=> release: update docs for v1.0.0-beta.2
